/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'surface-dim': '#cbdbf5',
        background: '#f8f9ff',
        'on-secondary-fixed': '#00201f',
        'surface-variant': '#d3e4fe',
        'tertiary-fixed-dim': '#a7cbe2',
        'surface-container-low': '#eff4ff',
        outline: '#70787d',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#c3e8ff',
        'on-surface': '#0b1c30',
        'on-secondary-fixed-variant': '#00504e',
        'secondary-fixed-dim': '#6ad8d4',
        'on-primary-fixed': '#001e2b',
        'outline-variant': '#c0c8cd',
        'on-tertiary-container': '#b0d5ec',
        'on-tertiary-fixed': '#001e2c',
        'secondary-fixed': '#88f4f0',
        'on-background': '#0b1c30',
        'inverse-surface': '#213145',
        secondary: '#006a68',
        'surface-bright': '#f8f9ff',
        'tertiary-container': '#3a5d71',
        tertiary: '#214558',
        'on-surface-variant': '#40484d',
        'surface-container-high': '#dce9ff',
        'secondary-container': '#85f1ed',
        'on-primary-container': '#9bd7f7',
        'surface-tint': '#236580',
        'inverse-primary': '#92cfee',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#eaf1ff',
        surface: '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#004d66',
        'on-secondary-container': '#006e6c',
        primary: '#00475e',
        'primary-fixed': '#c0e8ff',
        'surface-container-highest': '#d3e4fe',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#92cfee',
        'surface-container': '#e5eeff',
        'on-tertiary-fixed-variant': '#274b5e',
        'primary-container': '#1a5f7a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xl: '32px',
        'margin-mobile': '16px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        gutter: '16px',
        xs: '4px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'label-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
